server:
  port: 84

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        service-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'