server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000



ribbon:
  #指的是建立连接后从服务器获取资源所用的时间，超过就报错
  ReadTimeout: 5000
  #建立连接所用的时间，适用于正常情况下，两端链接所用的时间
  ConnectTimeout: 5000


